apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: argo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ghcr.io/mlflow/mlflow:v2.16.0
        ports:
        - containerPort: 5000
        command: ["mlflow", "server"]
        args:
          - "--backend-store-uri=sqlite:///mlflow.db"
          - "--default-artifact-root=gs://gke-bucket-name/mlflow/artifacts"
          - "--host=0.0.0.0"
          - "--port=5000"
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/service-account.json
        volumeMounts:
          - name: gcs-credentials
            mountPath: /var/secrets/google
            readOnly: true
      volumes:
      - name: gcs-credentials
        secret:
          secretName: gcs-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: argo
spec:
  selector:
    app: mlflow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort