apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
data:
  config: |
    artifactRepository:
      gcs:
        bucket: gcs-bucket-name  # GCS bucket name
        serviceAccountKeySecret:
          name: gcs-credentials  # Kubernetes secret containing your GCS credentials
          key: service-account.json  # key in the secret that contains the JSON credentials
    columns:
      - name: Workflow Completed
        type: label
        key: workflows.argoproj.io/completed
    executor:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
    images:
      docker/whalesay:v3.5.10:
         cmd: [cowsay]
    links:
      - name: Workflow Link
        scope: workflow
        url: http://logging-facility?namespace=${metadata.namespace}&workflowName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
      - name: Pod Link
        scope: pod
        url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
      - name: Pod Logs Link
        scope: pod-logs
        url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
      - name: Event Source Logs Link
        scope: event-source-logs
        url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
      - name: Sensor Logs Link
        scope: sensor-logs
        url: http://logging-facility?namespace=${metadata.namespace}&podName=${metadata.name}&startedAt=${status.startedAt}&finishedAt=${status.finishedAt}
      - name: Completed Workflows
        scope: workflow-list
        url: http://workflows?label=workflows.argoproj.io/completed=true
    metricsConfig:
      enabled: true
      path: /metrics
      port: 9090
    namespaceParallelism: 10
    retentionPolicy:
      completed: 10
      failed: 3
      errored: 3